### ISSUE TITLE
Bug: Password Reset Count Fails

### ISSUE THREAD

**Issue by stewrg** [tridentli/trident#112]
When using the CLI to try and reset the failed login count for a user I get the following error message and the password count does not appear to reset:

<img width="405" alt="screen shot 2017-06-14 at 09 08 21" src="https://user-images.githubusercontent.com/12988621/27122035-6a660d0c-50e1-11e7-898c-57ac3d7ed16e.png">

**Comment by bapril** [comment]
Closing as duplicate, already fixed in 1.4.6
Thanks
