### ISSUE TITLE
Bug: user password resetcount command fails from CLI

### ISSUE THREAD

**Issue by stewrg** [tridentli/trident#116]
Whenever I try to reset the failed password attempts from the CLI If get th following error screen:

<img width="349" alt="screen shot 2017-06-29 at 11 34 04" src="https://user-images.githubusercontent.com/12988621/27685252-525e7d30-5cc5-11e7-9c47-7a330da8ad04.png">

and the password fail count does not change (according to the log). Please repair as a priority.

**Comment by bapril** [comment]
Closing, this is fixed in 1.4.6

Thanks!
Ben
