### ISSUE TITLE
Unable to update - picture or PGP key

### ISSUE THREAD

**Issue by DLewisEE** [tridentli/trident#153]
I went to update my picture today and found I wasn't able to.  Additionally, my PGP key had expired and I went to replace it with my newly generated one (see below) and the format doesn't appear to be supported correctly.  The expire date now appears to be UNIX time 0.  

-----BEGIN PGP PUBLIC KEY BLOCK-----
Comment: User-ID:	<darian.lewis@protonmail.com>
Comment: a.k.a.:	<dlewisee@hotmail.com>
Comment: a.k.a.:	Darian Lewis <dlewisee@gmail.com>
Comment: Created:	3/26/2021 7:20 AM
Comment: Expires:	3/31/2023 12:00 PM
Comment: Type:	4,096-bit RSA (secret key available)
Comment: Usage:	Signing, Encryption, Certifying User-IDs
Comment: Fingerprint:	6E4199395893DAD05DC91F1F21833A48387F84E4

mQINBGBd0ZMBEAC+t+WExUCsZtNX35lQokry1AIwtgkUgu7gmooH8uyz3++z7z8A
tfiWxGPu2zsCu/GVECLRdfxcvxB0kNdaINIcHUzZlsxj6ucuJw0mjkjpXxzilhUW
SMH+Z6UqE2D6KKM/uA2MIPMbqRDi55g/opImF3DkA5qI0ab6roqSAAPAEWhNpU1c
a5yj6dtg1zpkFHuivxgLQMqx2b3tFfpSXPHAVcwoBWoGCUl+yKwl87XtQaQhpXYT
3eTpSKEJ0SmJpKg4ySYIjmvJ/9xxQU50rKXw8yRXjjCagcx95wk0OKNMk6/LykVu
K84Nwfvo6D+HKCRx4hKibQvo+LeufslH3lJRiXuRixXOHmDM7tnBSxiIPp+YaehR
Y8iQjjbrGXPyt+gLh8raf+pXalRZaGAibS52x6TYmTVXuI86uSqusXKeh8UPAKoK
R8hbz+M4LsBKXwvnuMe9tc0yqoWjhizBcHclM75veQ+I3gbkfG7y69fZsPFf32IH
tbwQizZWFuYu6xHsmP6t8YoxRXTBmfxsOg+gHPbjnCu2ljgHh85nUrHzO5468472
x4WKP3IfZFtiSy61xxRC24O/YQxp5zs0xPfGk00OLRv+FHPNQzkAzxs1M74g0H/6
vUnBPXNu/9KL5JznWbGLF2xcwI16//iggMoFBuD3TsCyuPdRtcN1raYFRQARAQAB
tBRkbGV3aXNlZUBob3RtYWlsLmNvbYkCVAQTAQgAPhYhBG5BmTlYk9rQXckfHyGD
Okg4f4TkBQJgXdTlAhsDBQkDyT/9BQsJCAcCBhUKCQgLAgQWAgMBAh4BAheAAAoJ
ECGDOkg4f4Tk7H8P+QHfBUEi+CvGNBboZLUAMTk4hbvjcJVfsSd928tDzRIfXTZX
RYTbBmpMxcHfp4EOuHqRTSDqxk2Am/J8CttgevQPowG9+wmC4SseT5C2uaca07yg
ELlhKPq8dC2UfmYp3/qPXH6jwKIE8Zg527metEyZVzXdkbXlGzvs0QbG0kJSYmOy
Mie6AzE9llBAKewPsGl26IWL0902eoh8HSrsiS8fEeie+vzm7JqKLI2zJNII22AU
/BomUX/jGylsp1+tdTRhKBsDJn9eKD4hdu9MU20b9dZO7NqXaBR8zldVYy/p/6Bq
qb3QrtFiU6DDVQOgUGiKE4FiKbQeIJQuOpwAeezpEKSfIATvSqN9JsgEcSHSdt1w
DpVBSZ6iJ9L4X5TNqGLzhLNViraf8JBG4kUgaRgblFz60pMGYB2xzR19vTYkH7hq
OcX28c9FppskF0HqPN5a4NLU7JsLUpkZrpItyQ7JXULwZN7iih6DlaTUBSDxNznL
g11iDKW5XsrwsA3qddcRDTJWbbHhoSddBvBLjjPd/q+IXddZ5cjZY50aEMMx6VPx
OpboJs3mztBQuUxs18IZEXvHKrt7ThhOov7mmqfQ+hLlWHz+hUSMRTZcoDfJe/kk
4mJ3ZL/Ar/G1hibn+BfagMa/nx2Dkp1qTwdPXpDPbVB/y2r4+LqLKiYOwqJftCFE
YXJpYW4gTGV3aXMgPGRsZXdpc2VlQGdtYWlsLmNvbT6JAlQEEwEIAD4WIQRuQZk5
WJPa0F3JHx8hgzpIOH+E5AUCYF3RkwIbAwUJA8k//QULCQgHAgYVCgkICwIEFgID
AQIeAQIXgAAKCRAhgzpIOH+E5ASZD/4nXy+t2Lrg91CBnrHjhj7H4bW4iwZojg0m
QOdOyfWWFahpIb5PMl2Qi2rvxfNXedhj94kfXhgMkspNhlF22C2qNtWOgoFQlH0A
7lePNE7hp1npf0siU0FyIhlfepwvpFDFsAsqvrTl0U4eXhJ4hYE+mgrw3nLH9g9U
Mim6G+rNACNzjkhPR6qytBrxpzQq8K7yIUmCBuF8Z1FGSFNzP+Ommahi/c6Y9R2g
Mq+NeotttQ/p74xTzO4u/xbWmj4S5RtZD+0c36I3EN4818LGFofJLiROF5tBOLvm
ZIMP/D4HGt1/nbjkG2nEwlojjPXK3m+Bp+y4FbcTnVU0kLvo1NvrKpxbNWhow+9I
w6NHKROPsL+gy5PhzF5I7zS8wW4sBFBaYpvb8O9W0j2wWf2vYVJ7xnB3eAhcddXE
KSs9627cCWKiJ6haaAbXNk0i8LYZyyamn8yEpUoE/tNyiCui2kaSrp4N5rAuAKET
QjIFwLfBvrGl+5uGi98KuSYYxCtzfO4ES5BwxdbydlMFZ3QiboxYlBKi08uf+xSh
pHH3H3f7ObIgaYa4gNNIlgInbwwbDcJSVMQlkf4csN2ifJ40Fxv/4Sgc4OpDr7xy
IJfOPzb19lkudtlvRmrZWGScOfEWhfyXaJELfweSfywyso8qIVWIVBNLJJXaIPUM
XcFMI3qy7bQbZGFyaWFuLmxld2lzQHByb3Rvbm1haWwuY29tiQJTBBMBCAA+FiEE
bkGZOViT2tBdyR8fIYM6SDh/hOQFAmBd1P8CGwMFCQPJP/0FCwkIBwIGFQoJCAsC
BBYCAwECHgECF4AACgkQIYM6SDh/hOT0rA/2NkpviQaiiqwZdCSYJ5kUT5T4pHH7
wrcVK2azRy7mStm8BiK7aqsBRyF3XN5Xqmrxs7ZkYPAYhPiZfP85XdMQ3sXZXQM5
BS+KTmQU564GeJrvi7D7Pu58XqMCVoOKoNJBxzxgMcZAyZNNMM+I3qYpUozsLsfW
oExK1Y4JpbRdQt0T9obhnR9H6qWujmKb0QJZBWJtGMXV3sNIjMhsk2cqnP1T002w
090X1tDWkSsEffElWdb0SlLCuLYwjx/GBaHpf9A9tMWJr6elRg918/YzQhU3fFXD
hhy6vrSuWEGUPQ0MKgza6pShEQJUGCsECKvIPiqFQ5B1/L6XYYm69RI5iVwk5BZO
e1F1OrAg9+XVWLflo+koPW2ZJsRf2oaYErxPgr2TTdZA2co+sL/wk6BuHI6tBn/6
cROY5xZfM5SS5ytSnv0uQzcwQLBb+YY+y4bIqwwzE7L4GvRD+/rC4x3NMlOJsVRN
ahFnvcJcgvj6SWkJ1RNcBgU2tKq5LvSEZykddWHX+DUo26p+EDGZSpJxzejrYWga
uzgl31wHK1DH9+5BgslfVqm55fLt9fb5ogug75+uyF2MtRMEbpxRWQvl7zMVXRuc
i4VxKVB7P/IhdMnHXv2kAwJZCCA8p83MlxhunHXOtkQIym9s5Aeq4TT71RBXbDdu
1xRwRRbb1Dt3S7kBjQRgXdGTAQwAnstaDOgb6DoX2Rtaw8mEepDZNZtOJ6XdNOMY
2kwK25pDf9D5fGD6P9W2d+/tE2frsHEOMPBQ7VVOBtRoLDdF+P+zcZjQanfcT3Dr
V0PeMSFocW2M3j5My6EqcTaYpUXn84kL8Ml4UUeK9qyUoL3P02PUWfiTV4RjB6eS
qJsHyte9qA/GIt6K+omih9K6YZ8Q2zXeql76RS6ONpBw+E1egQv+c1bMTLVr3dj5
UDRKaBQ+nECTEK7tK0gMinkopPkknCB1F/Go98jJczdlW2RUUOhn2VGty5WDNkIx
Z5fN8FoButYAaUoeJjKrIfwkn6mQYJELQxi6McSzHgVMKtDaqv1EWEZOPYZEZcBi
bf3qd9sLRxL4Bch2zYEP4o4zJ3EgMbmtlcZ2UErJ7aL5oZFC2wxdwoPqi7Mzzlt+
QlfxoMEyUMQQPOg+GlXt2K3mVlg+Ei85cfVkU1AL8qzAb7AR4G/HfjuIU+tU8AtR
BKF8My6DIDNQCN1CQlTOPTrtRIN/ABEBAAGJAjwEGAEIACYWIQRuQZk5WJPa0F3J
Hx8hgzpIOH+E5AUCYF3RkwIbDAUJA8k//QAKCRAhgzpIOH+E5NS4D/9zDhV0MQXb
WtGah6SEi4KFxtss3v0Ornookjs41zX5NnzxaywDg27oBpv42gI/RITg2sDl/nF3
YFkPYkn//l1/xR7wg28zLQQNN4qwd+Sp+ZyR4ROFq5mkDipSjyBY/Aniw101Fz2Z
kJzvMfPHFDR5tzeiqcUIx7jomxKfB4hkhqZs4DYpGHxmWThtQYsqfhGimU1YdU5k
5eI4dvUX3spySfnDUOXOP1Z5y30c4f5hLirfJn93XoFGubiWK4GlSHhnpnYbXl2R
fjBrOJ2c2GFUs9LEH2Z/N4C0yC5wOQ+Ofx8YghY2zdbwodpLjYkQtlvhZ5k5Xq01
i5QwPTXvtXwZxHTvM9JGGfRtu6kS8RS+dTUCnaXbfpdd1pEU/OweL92VSU5H9A2J
neRimHFbcyhK8JT+x1Yu/dEvQHCobc6vxbTgUoQ3poa7/+kk0ngkXrd2AWiwrObZ
ZCJTps0ppVZsjA/Gxu1eEfeyQ3zjs7skXHHgIel017UWK0SIVHKwyXN8eskAXSXw
r0yKgnLxrB69GfsrGpB7z4dSiSgaAgrtN+4gnVfh2/KDSPhDl33ntGmwBGccoV3V
YIiAaBm0O7U1zuBoVHZc20z9UgzvU8AFF64FDmY/tgbi8yzF+3Dw1pN/xQa7Wsk0
4Bw1iHLnR0KA7tkOU2pJIgjcn8e443+TdA==
=anae
-----END PGP PUBLIC KEY BLOCK-----

**Comment by massar** [comment]
Sounds like a problem with a specific instance, not a code.

You likely want to contact the administrators of the instance you are using.

Github is for code issues, not problems with a profile you have on an instance.

As you posted possibly private info, you might even want to remove this issue.
