### ISSUE TITLE
Sys-admin User Listing: Cannot advance to next page of user records

### ISSUE THREAD

**Issue by teward** [tridentli/trident#36]
When browsing the web portal as a SysAdmin user, and going to the "User" page to list all users, the "Forward" button to advance the offset by 10 to see the "next page" of users does nothing.

The system passes the argument of `offset=10` to the system, but the page does not advance to the next page of users.

**Comment by bapril** [comment]
This is fixed and waiting on review: https://github.com/tridentli/pitchfork/pull/46
