### ISSUE TITLE
Poor formatting on certain pages

### ISSUE THREAD

**Issue by teward** [tridentli/trident#40]
Hello.

There is a formatting issue on some subpages.  So far, I've replicated these issues on the 2FA Tokens page for a given token, and the user email editing page.  These make the GUI look a little weird, because input boxes expand beyond the edges of the tables.

Screenshots attached, while erasing some data from them with black lines.

2FA Token Edit page:
![te_2fa_bad](https://cloud.githubusercontent.com/assets/327952/21504383/7f5da6fa-cc2c-11e6-9033-e7f2ad6c4d76.png)

Email edit page for a specific email:
![email_te_bad](https://cloud.githubusercontent.com/assets/327952/21504387/8878cbd4-cc2c-11e6-8189-8d4a4132c02c.png)

**Comment by bapril** [comment]
Transfered to pitchfork. https://github.com/tridentli/pitchfork/issues/62
