### ISSUE TITLE
New notification fail if email contain upper case characters - Bug

### ISSUE THREAD

**Issue by stewrg** [tridentli/trident#59]
New notification fail if emails contain upper case characters

Each time I try to enter an email address that contains an upper case character I get the following error message: "Could not verify email address" - but it appears to work if I delete the 'half created' userID (using the CLI) then retry with the nominated email address all in lower case.

Is it possible to automatically convert all characters to lower case in the email submission box prior to having to enter all the remaining details only for things to fail - or deploy some other mechanism to avoid unnecessary fails.

**Comment by bapril** [comment]
Done in 1.4.5
