### ISSUE TITLE
There are some interesting log messages ... in syslog

### ISSUE THREAD

**Issue by morrowc** [tridentli/trident#63]
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Menu: No user,hidden permission for MenuPath(user): Not authenticated
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: NoAccess: Not Logged in
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Username<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Your username<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>user@example.com<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Password<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Your password<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>4.very/difficult_p4ssw0rd<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Two Factor Code<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Two Factor Token (if configured)<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>314159<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Comeback<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Required<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Cookies<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Sign In<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Message<<<
Jan 23 18:07:45 portal.usa3.ops-trust.net tridentd[32762]: 2017/01/23 18:07:45 Error: Translation missing trident.li/pitchfork/ui.login >>>Error<<<

I'm unclear as to whether or not these are important, probably no one cares and the logs shouldn't be made... or someone should scrape these out and 'do something' code-wise, yes?

**Comment by bapril** [comment]
These lines are ignorable for now. I have a plan to fix, but it's lower priority.

**Comment by bapril** [comment]
Corrected in 1.4.5
