### ISSUE TITLE
less than helpful command line (tcli)

### ISSUE THREAD

**Issue by morrowc** [tridentli/trident#65]
morrowc@portal.usa3:~$ tcli user get ident  kevinthomsen1585
kevinthomsen1585

really? I would never have guessed that the userid i put in is the userid of the user :(

I really want to know: "for user X what is their relevant data in the system?" I guess I can do that by asking for each in turn:
   image                <username>           Image - Upload an image of yourself, the system will scale it
 ident                <username>           User Name - The username of this user
 descr                <username>           Full Name - Full Name of this user
 name_first           <username>           First Name - The First Name of the user
 name_last            <username>           Last Name - The Last name of the user
 affiliation          <username>           Affiliation - Who the user is affiliated to
 post_info            <username>           Postal Details - Postal address or other such details
 sms_info             <username>           SMS - The phone number where to contact the user using SMS messages
 im_info              <username>           I.M. - Instant Messaging details
 tz_info              <username>           Timezone - Timezone details
 tel_info             <username>           Telephone - The phone number where to contact the user using voice messages
 airport              <username>           Airport - Closest airport for this user
 bio_info             <username>           Biography - Biography for this user
 sysadmin             <username>           System Administrator - Wether the user is a System Administrator
 login_attempts       <username>           Number of failed Login Attempts - How many failed login attempts have been registered
 no_email             <username>           Email Disabled - Email address is disabled due to SMTP errors
 hide_email           <username>           Hide email address - Hide my domain name when forwarding group emails, helpful for DMARC and SPF
 recover_email        <username>           Email Recovery address - The password used for recovering passwords
 furlough             <username>           Furlough - Extended holiday or furlough
 entered              <username>           Entered - Timestamp in UTC
 activity             <username>           Last Activity - Timestamp in UTC

(also, 'username' here means really 'ident', right? or it seems that way)

but that seems ... less helpful. This also doesn't tell me the user's associated email addresses, though I can find that in:
$ tcli user list username 

I can set a user's email per group with:
  $ tcli user email member set <username> <group> <email>

which seems cumbersome for 'change all delivery'... is there a way to do all delivery without a shell loop?

**Comment by morrowc** [comment]
$ for d in $(tcli user email member list floobart | awk '{print $1}'); do
> tcli user email member set floobart $d floobart@doggiefun.com
> done
Group email updated

is the loop I ended up using... 'group email updated' maybe is better stated as:
  "set user <floobart> email delivery in tg <floogroup> floobart@doggiefun.com"

or that'd be helpful to me, anyway.

**Comment by bapril** [comment]
I'll add a sysadmin only "user set_password $ident $password"
and a "user view $ident".
