### ISSUE TITLE
tsetup sudo commands fail after translation update. 

### ISSUE THREAD

**Issue by bapril** [tridentli/trident#73]
panic: no supported languages found []string{"en-US"}

goroutine 1 [running]:
panic(0x982da0, 0xc820280470)
        /opt/go-1.6.1/src/runtime/panic.go:464 +0x3e6
trident.li/pitchfork/lib.NewPfCtx(0xc68da8, 0xc68da0, 0xc68db0, 0x0, 0x0, 0x0, 0x0)
        /opt/dims/src/trident/ext/_gopath/src/trident.li/pitchfork/lib/ctx.go:222 +0x10b
trident.li/trident/src/lib.NewTriCtx(0x0, 0x0)
        /opt/dims/src/trident/ext/_gopath/src/trident.li/trident/src/lib/ctx.go:13 +0x5d
trident.li/pitchfork/cmd/setup.Setup(0xb40318, 0x6, 0xb402b8, 0x7, 0xb39710, 0x7, 0xc66f00, 0x5, 0xbd3900, 0x21, ...)
        /opt/dims/src/trident/ext/_gopath/src/trident.li/pitchfork/cmd/setup/setup.go:171 +0xa8c
main.main()
        /opt/dims/src/trident/src/cmd/tsetup/tsetup.go:22 +0xf5

**Comment by massar** [comment]
Reference: https://github.com/tridentli/pitchfork/issues/77

After that has been fixed, this should be resolved too.

**Comment by bapril** [comment]
Closing, doesn't appear to be the case in 1.4.6
